version: "3.9"
services:
  app:
    build: .
    networks:
      - mongonet
    environment:
      MONGO_URL: mongodb://localmongo:27017
      SERVICE_NAME: ${SERVICE_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: Asia/Kolkata
      MONGO_DATABASENAME: ${MONGO_DATABASENAME}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      PRICE_TACKER_URL: ${PRICE_TACKER_URL}

    command: tail -f /dev/null
    depends_on:
      - localmongo
    ports:
      - 3000:3000/tcp
  localmongo:
    image: mongo:5.0.6
    ports:
      - 60011:27017/tcp
    networks:
      - mongonet
networks:
  mongonet: {}
